name: Release file check

on:
  pull_request:
    types: [synchronize, reopened, opened, ready_for_review]
    branches:
    - main

jobs:
  release-file-check:
    runs-on: ubuntu-latest

    outputs:
      changelog: ${{ steps.release-check.outputs.changelog }}

    steps:
    - uses: actions/checkout@v1

    - name: Release file check
      uses: ./.github/release-check-action
      id: release-check
        # if: github.event.pull_request.draft == false

  generate-preview:
    runs-on: ubuntu-latest
    needs: release-file-check

    steps:
    - name: Generate Twitter card preview
      uses: strawberry-graphql/release-cards@main
      with:
        version: "(next)"
        contributor: ${{ github.event.pull_request.user.login }}
        description: ${{ fromJSON(needs.release-file-check.outputs.changelog) }}

    - name: Uploads preview to imgur
      run: |
        echo 'set-output::release_card_url=$(curl --location --request POST "https://api.imgur.com/3/image" \
          --fail \
          --header "Authorization: Client-ID $IMGUR_CLIENT_ID" \
          --form "image=@screenshot.png;filename=screenshot.png;type=image/png" \
          | jq  --raw-output '.data.link')'
      env:
        IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}

  send-comment:
    runs-on: ubuntu-latest
    needs: [release-file-check, generate-preview]

    steps:
    - uses: actions/checkout@v1
    - name: Send comment
      uses: ./.github/bot-action
      with:
        pr_number: ${{ github.event.number }}
        status: "OK"
        change_type: "PATCH"
        changelog: "demo"
