name: Release file check

on:
  pull_request:
    types: [synchronize, reopened, opened, ready_for_review]
    branches:
    - main

jobs:
  release-file-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Release file check
      uses: ./.github/release-check-action
        # if: github.event.pull_request.draft == false

    - name: Generate Twitter card preview
      uses: strawberry-graphql/release-cards@main
      with:
        version: "Next"
        contributor: ${{ github.event.pull_request.user.login }}
        description: ${{ env.CHANGELOG }}

    - name: Uploads preview to imgur
      run: |
        echo IMAGE_URL=$(curl --location --request POST "https://api.imgur.com/3/image" \
          --fail \
          --header "Authorization: Client-ID $IMGUR_CLIENT_ID" \
          --form "image=@screenshot.png;filename=screenshot.png;type=image/png" \
          | jq  --raw-output '.data.link') >> $GITHUB_ENV
      env:
        IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
    - uses: mshick/add-pr-comment@v1
      with:
        message: |
          **Hello**
          🌏
          ![](${{ env.IMAGE_URL }})
          !
        repo-token: ${{ secrets.BOT_TOKEN}}
        repo-token-user-login: 'botberry'
        allow-repeats: false
