name: Release file check

on:
  pull_request:
    types: [synchronize, reopened, opened, ready_for_review]
    branches:
    - main

jobs:
  release-file-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Release file check
      uses: ./.github/release-check-action
      id: release-check
        # if: github.event.pull_request.draft == false

    - name: Generate Twitter card preview
      uses: strawberry-graphql/release-cards@main
      with:
        version: "(next)"
        contributor: ${{ github.event.pull_request.user.login }}
        description: ${{ steps.release-check.outputs.changelog }}

    - name: Uploads preview to imgur
      run: |
        echo IMAGE_URL=$(curl --location --request POST "https://api.imgur.com/3/image" \
          --fail \
          --header "Authorization: Client-ID $IMGUR_CLIENT_ID" \
          --form "image=@screenshot.png;filename=screenshot.png;type=image/png" \
          | jq  --raw-output '.data.link')
      env:
        IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
